# Resume settings
resume_avatar:                  "false"
resume_name:                    "Daniel Wright"
resume_title:                   "Blue-Sky Solutioneer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dan.wright@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "503-765-4451"
resume_contact_address:         "Portland, or"

resume_header_contact_info: |
  Portland, OR •
  <a href="tel:503-765-4451">503-765-4451</a> •
  <a href="mailto:dan.wright@gmail.com">dan.wright@gmail.com</a>

display_header_contact_info:    "true"

resume_header_intro: |
  <p>Rubyist-errant. TDD enthusiast. Extensive experience in launching and supporting ecommerce startups. Burgeoning passion for infrastructure automation and operationalizing software at scale. Incorrigible problem-solver.</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/DanielWright"
  resume_twitter_url:           "http://twitter.com/Hobonium"
  resume_linkedin_url:          "https://www.linkedin.com/in/daniel-hh-wright"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
